### ISSUE TITLE
util has no attributes get_batches

### ISSUE THREAD

**Issue by ariaaay** [LukasMut/VICE#12]
Hi, I was running the provided evaluation code and ran into the following error.

```
Traceback (most recent call last):
  File "VICE/main_robustness_eval.py", line 312, in <module>
    evaluate_models(
  File "VICE/main_robustness_eval.py", line 237, in evaluate_models
    val_batches = utils.get_batches(
                  ^^^^^^^^^^^^^^^^^
AttributeError: module 'utils' has no attribute 'get_batches'
```

Could you point me to this function? Thanks!

**Comment by LukasMut** [comment]
Sorry for the late response! Fixed it! It should work now.
